// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGIxUjepFTf7xW1-FiK7PwfduXmLqgbSo',
    appId: '1:757872933264:web:b8828e164e42cb059b5b15',
    messagingSenderId: '757872933264',
    projectId: 'visual-ease',
    authDomain: 'visual-ease.firebaseapp.com',
    storageBucket: 'visual-ease.appspot.com',
    measurementId: 'G-WY8QLV9E1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUdBCI1wOXjZrmwbt85jtAGO649sk50j0',
    appId: '1:757872933264:android:6e0dd30b963043789b5b15',
    messagingSenderId: '757872933264',
    projectId: 'visual-ease',
    storageBucket: 'visual-ease.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJQXIQl1LW5KSbW_Gy9Q8VbKlW86sggdw',
    appId: '1:757872933264:ios:38adf4c1213813929b5b15',
    messagingSenderId: '757872933264',
    projectId: 'visual-ease',
    storageBucket: 'visual-ease.appspot.com',
    iosClientId: '757872933264-b403ecpl590a7ktfkmfnctegeer0kmii.apps.googleusercontent.com',
    iosBundleId: 'com.example.visualEaseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJQXIQl1LW5KSbW_Gy9Q8VbKlW86sggdw',
    appId: '1:757872933264:ios:38adf4c1213813929b5b15',
    messagingSenderId: '757872933264',
    projectId: 'visual-ease',
    storageBucket: 'visual-ease.appspot.com',
    iosClientId: '757872933264-b403ecpl590a7ktfkmfnctegeer0kmii.apps.googleusercontent.com',
    iosBundleId: 'com.example.visualEaseFlutter',
  );
}
