name: visual_ease_flutter
description: An app build with the stacked framework

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #App specific
  path_provider: ^2.0.14
  image_picker: ^0.8.7+1
  file_picker: ^5.2.7
  http: ^0.13.5
  perfect_volume_control: ^1.0.5
  geolocator: ^7.1.0
  geocoding: ^2.1.0
  permission_handler: ^10.2.0
  camera: ^0.10.4
  image: ^4.0.15
  google_maps_flutter: ^2.2.5


  # ML
  google_mlkit_image_labeling: ^0.5.0
  flutter_face_api: ^5.1.3
  flutter_face_core: 5.1.0
  flutter_tts: ^3.6.3


  # UI
  cupertino_icons: ^1.0.2
  flutter_signin_button: ^2.0.0
  lottie: ^2.2.0

  #Firebase
  firebase_core: ^2.8.0
  cloud_firestore: ^4.4.5
  firebase_storage: ^11.1.0
#  firebase_database: ^10.0.6
  
  # Stacked
  stacked: ^3.2.7
  stacked_services: ^1.0.2
  stacked_firebase_auth: ^2.19.2

  #Basics
  logger: ^1.3.0
  flutter_native_splash: ^2.2.19

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash.png

# flutter pub run flutter_launcher_icons
flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon.png"
  #    background_color: "#hexcode"
  #    theme_color: "#hexcode"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.12.0

  flutter_lints: ^1.0.0
  build_runner: ^2.2.0

  stacked_generator: ^1.0.0
  mockito: ^5.3.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/lottie/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Italic.ttf